server.port=${PORT:8080}
spring.application.name=clube-esportivo-api
spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
jwt.secret=ba567f1a8e02227e0b7e6c6933d3eaa6cb419c1212f8e8d19b8df90e3d2c7b2e
